# -*- coding: utf-8 -*-
"""job app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJKtpvTqf8uEEL_OtXWvUf8s3rLodI9W
"""

!pip install streamlit
import streamlit as st
import pandas as pd

st.title("Job Listing Clusters")

df = pd.read_csv('clustered_jobs.csv')
clusters = df['Cluster'].unique()

cluster_selected = st.sidebar.multiselect("Select clusters", clusters)

if cluster_selected:
    filtered = df[df['Cluster'].isin(cluster_selected)]
    st.write(filtered)
else:
    st.write(df)